apiVersion: v1
kind: ServiceAccount
metadata:
  name: dam-transform-worker
  namespace: {{ include "dam.namespace" . }}
  labels:
    {{- include "dam.labels" . | nindent 4 }}
  annotations:
    # Set to the value of: terraform output dam_worker_irsa_role_arn
    eks.amazonaws.com/role-arn: {{ .Values.transformWorker.irsaRoleArn | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dam-export-worker
  namespace: {{ include "dam.namespace" . }}
  labels:
    {{- include "dam.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.exportWorker.irsaRoleArn | quote }}
