# Dev environment overrides.
# Usage: helm install dam ./helm/dam -f app/helm/dam/values-dev.yaml --set ...

global:
  namespace: dam-dev

api:
  replicas: 1
  s3Bucket: "dam-assets-395675597879-dev"

web:
  replicas: 1

transformWorker:
  replicas: 1
  pollIntervalMs: "3000"
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

exportWorker:
  replicas: 1
  pollIntervalMs: "3000"

image:
  pullPolicy: Always
