# Staging environment overrides.
# Usage: helm upgrade dam ./app/helm/dam -f app/helm/dam/values-stg.yaml --reuse-values

api:
  replicas: 1
  s3Bucket: "dam-assets-395675597879-stg"

web:
  replicas: 2

transformWorker:
  replicas: 1
  pollIntervalMs: "5000"

exportWorker:
  replicas: 1
  pollIntervalMs: "5000"

image:
  pullPolicy: IfNotPresent
