apiVersion: v1
kind: Secret
metadata:
  name: dam-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  JWT_REFRESH_SECRET: {{ .Values.secrets.jwtRefreshSecret | quote }}
