apiVersion: v1
kind: ServiceAccount
metadata:
  name: dam-transform-worker
  namespace: {{ .Values.global.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.transformWorker.irsaRoleArn | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dam-export-worker
  namespace: {{ .Values.global.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.exportWorker.irsaRoleArn | quote }}
