apiVersion: v1
kind: Service
metadata:
  name: dam-api
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  selector:
    app: dam-api
  ports:
    - port: 3000
      targetPort: 3000
