apiVersion: v1
kind: Service
metadata:
  name: dam-api
  namespace: {{ .Values.global.namespace }}
  labels:
    app: dam-api
spec:
  type: ClusterIP
  selector:
    app: dam-api
  ports:
    - name: http
      port: 3000
      targetPort: 3000
